import { z } from 'zod'

// zod schemas for the Storage Connection onboarding endpoints (issue
// #150): a two-step launch/confirm flow rather than a single submission —
// the User only ever supplies their own AWS Account ID (not a secret, and
// not anything pasted back out of AWS afterwards); everything else
// (external_id/bucket/role_arn) is generated by Pictacular itself and
// round-tripped through the signed `pending_token` these schemas guard.
// "Connect an existing bucket" mode is deferred to issue #152, alongside
// re-adding a matching schema variant.
export const storageConnectionLaunchSchema = z.object({
  aws_account_id: z.string().regex(/^\d{12}$/, 'validation.invalid_aws_account_id'),
})

export const storageConnectionConfirmSchema = z.object({
  pending_token: z.string().min(1),
})

export type StorageConnectionLaunchInput = z.infer<typeof storageConnectionLaunchSchema>
export type StorageConnectionConfirmInput = z.infer<typeof storageConnectionConfirmSchema>
