import { z } from 'zod'

// zod schemas for the Storage Connection onboarding endpoints (issue
// #150/#152): a two-step launch/confirm flow rather than a single
// submission — the User only ever supplies their own AWS Account ID (not
// a secret, and not anything pasted back out of AWS afterwards) plus,
// for "connect an existing bucket" mode, that bucket's own name (the only
// value Pictacular can't generate/predict itself); everything else
// (external_id/generated bucket/role_arn) is generated by Pictacular
// itself and round-tripped through the signed `pending_token` these
// schemas guard. A discriminated union on `mode` mirrors the shape the
// legacy (pre-#150) single-step `storageConnectionSchema` already used
// for the same create/connect split.
const awsAccountIdSchema = z.string().regex(/^\d{12}$/, 'validation.invalid_aws_account_id')

export const storageConnectionLaunchSchema = z.discriminatedUnion('mode', [
  z.object({
    mode: z.literal('create'),
    aws_account_id: awsAccountIdSchema,
  }),
  z.object({
    mode: z.literal('connect'),
    aws_account_id: awsAccountIdSchema,
    bucket: z.string().min(1, 'validation.bucket_required'),
  }),
])

export const storageConnectionConfirmSchema = z.object({
  pending_token: z.string().min(1),
})

export type StorageConnectionLaunchInput = z.infer<typeof storageConnectionLaunchSchema>
export type StorageConnectionConfirmInput = z.infer<typeof storageConnectionConfirmSchema>
