#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4

banner "Storage Connection CloudFormation template hosting (issue #146)"

say "CloudFormation's own Launch Stack flow refuses any TemplateURL that isn't"
say "an S3 object (raw.githubusercontent.com fails with \"TemplateURL must be a"
say "supported URL\") — this sets up a public-read S3 bucket in Pictacular's"
say "own AWS account (310649435248, see docs/aws-account-setup.md) to host"
say "cloudformation/create-bucket.yaml and connect-bucket.yaml, and writes its"
say "base URL to NUXT_AWS_CFN_TEMPLATES_BASE_URL."
say "Sign in to the AWS Console as Pictacular's account (310649435248) first."

# ── Stage 1: create the bucket ─────────────────────────────────────────────
stage "Create the S3 bucket"
open_url "https://s3.console.aws.amazon.com/s3/bucket/create"
step "Bucket name: something globally unique, e.g. pictacular-cfn-templates."
step "Region: pick any (e.g. eu-west-1) — unrelated to Users' own bucket regions."
step "Under 'Block Public Access settings for this bucket', UNCHECK 'Block all"
step "public access' (the templates must be anonymously readable for the AWS"
step "Console's Launch Stack flow to fetch them) and acknowledge the warning."
step "Leave everything else default, then click 'Create bucket'."
ask CFN_BUCKET_NAME "Bucket name you created:"
ask CFN_BUCKET_REGION "Region you created it in (e.g. eu-west-1):"
pause "Bucket created?"

# ── Stage 2: public-read bucket policy ─────────────────────────────────────
stage "Allow public read on the bucket"
open_url "https://s3.console.aws.amazon.com/s3/buckets/${CFN_BUCKET_NAME}?tab=permissions"
step "Scroll to 'Bucket policy' → Edit, and paste the policy below, then Save:"
say ""
say "{"
say "  \"Version\": \"2012-10-17\","
say "  \"Statement\": [{"
say "    \"Sid\": \"PublicReadCfnTemplates\","
say "    \"Effect\": \"Allow\","
say "    \"Principal\": \"*\","
say "    \"Action\": \"s3:GetObject\","
say "    \"Resource\": \"arn:aws:s3:::${CFN_BUCKET_NAME}/*\""
say "  }]"
say "}"
say ""
pause "Policy saved?"

# ── Stage 3: upload the templates ──────────────────────────────────────────
stage "Upload the CloudFormation templates"
open_url "https://s3.console.aws.amazon.com/s3/buckets/${CFN_BUCKET_NAME}?tab=objects"
step "Click 'Upload' → 'Add files', and select both:"
step "  $(cd "$(dirname "$0")/.." && pwd)/cloudformation/create-bucket.yaml"
step "  $(cd "$(dirname "$0")/.." && pwd)/cloudformation/connect-bucket.yaml"
step "Click 'Upload'. Re-run this stage (re-run the whole script) after any"
step "future change to either file under cloudformation/ — nothing keeps this"
step "bucket in sync automatically yet."
pause "Both files uploaded?"

# ── Stage 4: wire up the env var + verify ──────────────────────────────────
stage "Save the base URL and verify"
CFN_TEMPLATES_BASE_URL="https://${CFN_BUCKET_NAME}.s3.${CFN_BUCKET_REGION}.amazonaws.com"
write_env NUXT_AWS_CFN_TEMPLATES_BASE_URL "$CFN_TEMPLATES_BASE_URL"
say "Verifying both templates are publicly reachable..."
for f in create-bucket.yaml connect-bucket.yaml; do
  url="${CFN_TEMPLATES_BASE_URL}/${f}"
  code=$(curl -s -o /dev/null -w '%{http_code}' "$url" || echo "000")
  if [[ "$code" == "200" ]]; then
    printf '  %s✓%s %s → HTTP %s\n' "$GREEN" "$RESET" "$url" "$code"
  else
    warn "$url → HTTP $code (expected 200 — check the bucket policy/upload)"
    SKIPPED+=("verify $url returned $code, not 200")
  fi
done
say "Restart 'npm run dev' to pick up the new .env value."
# ──────────────────────────────────────────────────────────────────────────

finish
